### PR TITLE
Differentiate keyed probes from regular probes

### LINKED ISSUE #127: Search.content probes should be labeled as keyed_scalars
The probes https://probes.telemetry.mozilla.org/?search=search.content are all set to type `scalars` but are actually found in `keyed_scalars` - the link to query them in telemetry.main therefore does not work.

### PR DESCRIPTION
**Pull request by Iinh**
Make it more clear when a probe is keyed and get the correct BigQuery tables for keyed probes. Also fixes #127, #125, #121.

### CODE REVIEW

**Comment by chutten** [comment]
Would it be within scope to also adjust to call them `keyed scalar` and `keyed histogram` in the search results table as well? 

And to fix the `Keyed: ` field in the detail view (which is currently [empty](https://probes.telemetry.mozilla.org/?search=search.content&view=detail&probeId=scalar%2Fbrowser.search.content.about_home)

**Comment by Iinh** [comment]
>  Would it be within scope to also adjust to call them keyed scalar and keyed histogram in the search results table as well?
> And to fix the Keyed: field in the detail view (which is currently [empty](https://probes.telemetry.mozilla.org/?search=search.content&view=detail&probeId=scalar%2Fbrowser.search.content.about_home).

Yup within scope. I'll add them to the fix.

**Comment by Iinh** [comment]
I decided to add a new field to the JSON data called `detailed_type` to be shown in search and probe detail page (mutating the current `type` field to include the word "keyed" where applicable breaks things because we use it in various places).

The new search page includes the detailed types:

CleanShot 2022-09-14 at 13 01 42@2x

Keyed scalar detail page:

CleanShot 2022-09-14 at 13 00 38@2x

Keyed histogram page:

CleanShot 2022-09-14 at 13 01 11@2x

File: src/components/probeDetails.jsx [hunk 1]
```diff
@@ -351,7 +353,7 @@ class ProbeDetails extends Component {
               {getExtraProbeDetails(probe, probeInfo).map(detail => (
                 <tr key={detail.label}>
                   <td className="fit pr-2">{detail.label}:</td>
-                  <td className="grow">{detail.content}</td>
+                  <td className="grow">{detail.content.toString()}</td>
```
Comment (Iinh) [inline src/components/probeDetails.jsx:358]: This fixes the bug of `Keyed` boolean field not showing. [The variables of `detail.content`](https://github.com/mozilla/probe-dictionary/blob/main/src/components/probeDetails.jsx#L201-L213) are all string-like values so adding an extra `toString()` step is safe.

File: src/main.jsx [hunk 2]
```diff
@@ -178,6 +178,14 @@ class Main extends Component {
           history = history.filter(m => m.optout);
         }
 
+        // Add a detailed type to differentiate between regular and keyed probes
+        if (history[0]["details"]["keyed"]) {
+          // Ensure that we only add the word "keyed" once, since React lifecycle can call this method multiple times
```
Comment (chutten) [inline src/main.jsx]: I'm not sure why this is needed since we're adding the word "keyed" to the value of `type` and storing it in `detailed_type` where we only ever read it for display... there should be no possibility of doubling up, right?

**Review by chutten — APPROVED** [review]
LGTM, I have one comment that wouldn't affect anything one way or the other.

File: src/main.jsx (hunk 2 above)
Comment (Iinh) [reply src/main.jsx]: you're right! This check was only needed in a previous iteration of the solution, in which I used `type` for display instead of creating a new field `detailed_type`.

**Comment by Iinh** [comment]
Will check on [stage](https://probedict-stage.bespoke.nonprod.dataops.mozgcp.net/) to make sure everything works fine before doing a prod deployment.
